name: create release binaries

on:
  release:
    types:
      - published

jobs:
  linux:
    name: create linux binary
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          set -eu
          wget https://github.com/bazelbuild/bazelisk/releases/download/v1.7.5/bazelisk-linux-amd64
          chmod +x bazelisk-linux-amd64
          ./bazelisk-linux-amd64 build //:bazel-remote
          ls -lR
#      - name: upload linux binary
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: bazelisk-linux-amd64
#          asset_name: bazelisk-linux-amd64
#
#  mac:
#    name: create mac binary
#    runs-on: macos-10.15
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Build
#        run: |
#          set -eu
#          wget https://github.com/bazelbuild/bazelisk/releases/download/v1.7.5/bazelisk-darwin-amd64
#          chmod +x bazelisk-darwin-amd64
#          ./bazelisk-darwin-amd64 build //:bazel-remote
#          ls -lR
